num_1 = int(input("First Number : "))
num_2 = int(input("Second Number : "))
print(num_1, "+", num_2, "=", num_1 + num_2)
print(num_1, "-", num_2, "=", num_1 - num_2)
print(num_1, "*", num_2, "=", num_1 * num_2)
print(num_1, "/", num_2, "=", num_1 / num_2)
